eureka:
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/
  instance:
    lease-expiration-duration-in-seconds: 12
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: server_a
        uri: lb://server-a
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1
        